import type { VinylRecord } from './types';

type SampleRecord = Omit<VinylRecord, 'id' | 'createdAt' | 'updatedAt'>;

export const sampleRecords: SampleRecord[] = [
  {
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    year: 1973,
    format: 'LP',
    condition: 'VG+',
    colorVariant: 'Black, original UK pressing',
    purchasePrice: 85,
    purchaseDate: '2022-03-15',
    notes: 'Harvest Records first press. Includes both posters and stickers. Slight ring wear on jacket.',
    coverUrl: 'https://coverartarchive.org/release/a2016fb7-3e39-4cd7-9fa3-5cc28fdee4f0/front-250',
    barcode: '',
  },
  {
    artist: 'The Beatles',
    album: 'Abbey Road',
    year: 1969,
    format: 'LP',
    condition: 'VG',
    colorVariant: 'Black',
    purchasePrice: 45,
    purchaseDate: '2021-11-20',
    notes: 'Apple Records repress. Some surface noise on Side B but plays through fine.',
    coverUrl: 'https://coverartarchive.org/release/27f534f7-12c5-4c56-8dda-39fbdad10c17/front-250',
    barcode: '',
  },
  {
    artist: 'Fleetwood Mac',
    album: 'Rumours',
    year: 1977,
    format: 'LP',
    condition: 'NM',
    colorVariant: 'Black, 2011 remaster',
    purchasePrice: 28,
    purchaseDate: '2023-06-10',
    notes: 'Warner Bros 180g repress. Sounds incredible. Best $28 ever spent.',
    coverUrl: 'https://coverartarchive.org/release/5c976ee2-d4d4-4932-8f16-54f2b50f8ac5/front-250',
    barcode: '',
  },
  {
    artist: 'Miles Davis',
    album: 'Kind of Blue',
    year: 1959,
    format: 'LP',
    condition: 'VG+',
    colorVariant: 'Blue translucent, limited edition',
    purchasePrice: 35,
    purchaseDate: '2023-01-05',
    notes: 'Columbia Legacy reissue on blue vinyl. Perfect late-night listening.',
    coverUrl: 'https://coverartarchive.org/release/e32a3f0b-1c19-3170-bb1c-650893774744/front-250',
    barcode: '',
  },
  {
    artist: 'Radiohead',
    album: 'OK Computer',
    year: 1997,
    format: 'LP',
    condition: 'NM',
    colorVariant: 'Black',
    purchasePrice: 32,
    purchaseDate: '2022-09-18',
    notes: 'XL Recordings reissue. Double LP, gatefold. Paranoid Android still hits different on vinyl.',
    coverUrl: 'https://coverartarchive.org/release/4b3d18cc-8937-36f4-8de0-481088be58e6/front-250',
    barcode: '',
  },
  {
    artist: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    format: 'LP',
    condition: 'VG+',
    colorVariant: 'Black, 2009 remaster',
    purchasePrice: 25,
    purchaseDate: '2021-04-22',
    notes: 'DGC/Sub Pop reissue. 180g pressing. Smells Like Teen Spirit intro on vinyl is a religious experience.',
    coverUrl: 'https://coverartarchive.org/release/7fb7f5b1-1b4a-4179-a14a-27af0ad53ca7/front-250',
    barcode: '',
  },
  {
    artist: 'Daft Punk',
    album: 'Random Access Memories',
    year: 2013,
    format: 'LP',
    condition: 'M',
    colorVariant: 'Black, original pressing',
    purchasePrice: 40,
    purchaseDate: '2023-08-30',
    notes: 'Columbia Records double LP. Still sealed until last week. Get Lucky groove is pure gold.',
    coverUrl: 'https://coverartarchive.org/release/c84b0559-8fce-43f0-8939-05e9e4e9f608/front-250',
    barcode: '',
  },
  {
    artist: 'Amy Winehouse',
    album: 'Back to Black',
    year: 2006,
    format: 'LP',
    condition: 'NM',
    colorVariant: 'Black, 180g',
    purchasePrice: 22,
    purchaseDate: '2022-12-25',
    notes: 'Island Records. Christmas gift. Rehab sounds even better analog. A masterpiece.',
    coverUrl: 'https://coverartarchive.org/release/1a6ecd02-a613-4239-abbe-21da23149fa6/front-250',
    barcode: '',
  },
  {
    artist: 'Tame Impala',
    album: 'Currents',
    year: 2015,
    format: 'LP',
    condition: 'NM',
    colorVariant: 'Red & Blue splatter',
    purchasePrice: 55,
    purchaseDate: '2024-02-14',
    notes: 'Modular Recordings limited color variant. The Less I Know The Better is a vibe.',
    coverUrl: 'https://coverartarchive.org/release/0060b94a-44e5-4cd8-9c47-ae15c44f5a5c/front-250',
    barcode: '',
  },
  {
    artist: 'Kendrick Lamar',
    album: 'To Pimp a Butterfly',
    year: 2015,
    format: 'LP',
    condition: 'VG+',
    colorVariant: 'Black',
    purchasePrice: 30,
    purchaseDate: '2023-05-12',
    notes: 'Aftermath/Interscope double LP. Alright is the anthem of a generation. Gatefold jacket.',
    coverUrl: 'https://coverartarchive.org/release/ba1050d3-0232-4d28-b7f8-50e3a7ea7bff/front-250',
    barcode: '',
  },
];
